import Link from "next/link";
import Head from 'next/head'
import Header from "@/components/header/header";
import styles from '../styles/feature.module.css'
import Footer from "@/components/footer/footer";

export default function feature(){

    return(
        <>
        <Head>
        <title>Time Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg"/>
      </Head>
      
<Header/>

      <main className={styles.feature_main}>
           <h1>Our Core Features</h1>
           
           <div className={styles.features}>
            
             <div className={styles.feature_section}>
                 <div>
               <img className={styles.feature_pic} src="/image/icon2.jpeg"/>
                 </div>
                 <p className={styles.feature_title}>Adding/Assigning Events</p>
                 <p className={styles.feature_description}>able to add/assign events through the app when nobody has events</p>
                
             </div> 

             <div className={styles.feature_section}>
                <div>
              <img className={styles.feature_pic} src="/image/icon1.jpeg"/>
                </div>
                <p className={styles.feature_title}>Groups</p>
                <p className={styles.feature_description}>able to invite people by username or email</p>
            </div> 

            <div className={styles.feature_section}>
                <div>
              <img className={styles.feature_pic} src="/image/icon3.jpeg"/>
                </div>
                <p className={styles.feature_title}>List View</p>
                <p className={styles.feature_description}>List View</p>
            </div> 

            <div className={styles.feature_section}>
                <div>
              <img className={styles.feature_pic} src="/image/icon4.jpeg"/>
                </div>
                <p className={styles.feature_title}>Menu Overlay</p>
                <p className={styles.feature_description}>Menu overlay available that can let u</p>
            </div> 
            
            <div className={styles.feature_section}>
                <div>
              <img className={styles.feature_pic} src="/image/icon5.jpeg"/>
                </div>
                <p className={styles.feature_title}>Chat</p>
                <p className={styles.feature_description}>able to chat with users through the app</p>
            </div> 

            <div className={styles.feature_section}>
                <div>
              <img className={styles.feature_pic} src="/image/icon6.jpeg"/>
                </div>
                <p className={styles.feature_title}>Public and Private view</p>
                <p className={styles.feature_description}>able to choose the calender to be public or private</p>
            </div> 
            
           </div>
        </main>   

<div className={styles.footer}>
<Footer/>
</div>


        </>
    )
}