import Link from "next/link";
import Head from 'next/head'
import Header from "@/components/header/header";
import styles from '../styles/feedback.module.css'
import Footer from "@/components/footer/footer";

export default function Feedback(){

    return(
        <>

      <Head>
        <title>Time Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg"/>
      </Head>


      <Header/>

<main className={styles.feedback_main}>



<p>Your feedback help us to improve our App!!</p>


<div className={styles.feedback_name_email}>

<div className={styles.feedback_section}>
<label>Name:</label>
<input type="text" required/>
</div>

<div className={styles.feedback_section}>
<label>Email:</label>
<input type="text" required/>
</div>
</div>

<div className={styles.feedback_section}>
<label>Feedback:</label>
<textarea required></textarea>
</div>

<div className={styles.feedback_section}>

    <div>
<label>Rate Our App:</label>
    </div>

<section className={styles.rating}>
    <div className={styles.rate_each_section}>
    <img className={styles.rate_pic} src="/image/rate5.png"/>
      <div className={styles.rate_each_section_texts}>
    <input type="radio" name="rating" value="5"/>
    <label className={styles.rate_number}>5</label>
      </div>
    </div>

    <div className={styles.rate_each_section}>
        <img className={styles.rate_pic} src="/image/rate4.png"/>
          <div className={styles.rate_each_section_texts}>
        <input type="radio" name="rating" value="4"/>
        <label className={styles.rate_number}>4</label>
          </div>
        </div>

        <div className={styles.rate_each_section}>
            <img className={styles.rate_pic} src="/image/rate3.png"/>
              <div className={styles.rate_each_section_texts}>
            <input type="radio" name="rating" value="3"/>
            <label className={styles.rate_number}>3</label>
              </div>
            </div>

            <div class="rate_each_section">
                <img class="rate_pic" src="/image/rate2.png"/>
                  <div className={styles.rate_each_section_texts}>
                <input type="radio" name="rating" value="2"/>
                <label className={styles.rate_number}>2</label>
                  </div>
                </div>

                <div class="rate_each_section">
                    <img class="rate_pic" src="/image/rate1.png"/>
                      <div className={styles.rate_each_section_texts}>
                    <input type="radio" name="rating" value="1"/>
                    <label className={styles.rate_number}>1</label>
                      </div>
                    </div>

</section>
    
</div>

<Link href="./thankYou">
 <button className={styles.submit_button}>Submit!</button>
</Link>
</main>

<div className={styles.footer}>
<Footer/>
</div>
        
        </>
    )
}