import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header/header'
import Link from 'next/link'
import Footer from '@/components/footer/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Time Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg"/>
      </Head>


      <Header/>
      
      <main className={styles.main}>

      <section className={styles.homepage}>
  <div className={styles.homepage_texts_section}>
    <h1>Time Together</h1>
    <h2>"Time you can all spend Together"</h2>


    <div className={styles.homepage_texts_section_buttons}>
      <Link href="https://timetogether-calender.netlify.app/">
        <button className={styles.button}>Download the app</button>
      </Link>

      <Link href="./video">
        <button className={styles.button}>Learn More</button>
      </Link>

    </div>

  </div>

     <div className={styles.homepage_screendisplay_section}>

        <div className={styles.picture1}>
        <img src="/image/homepage_pic1.png"/>
        </div>

        <div className={styles.picture2}>
        <img src="/image/homepage.png"/>
       </div>
     </div>

</section>
    
      </main>

<div className={styles.footer}>
<Footer/>
</div>

    </>
  )
}
