import Link from "next/link";
import Image from "next/image";
import Head from 'next/head'
import styles from '../styles/members.module.css'
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export default function Results(){

    return(
        <>


      <Head>
        <title>Time Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg"/>
      </Head>
      
        <Header/>

          <main className={styles.main_members}>
                <div className={styles.background}>
                    <h1>Meet Our Designers</h1>
                    
                    <div className={styles.membersContainer}>
                        <div className={styles.members}>
                            <section className={styles.mariessa_section}>
                                <img src="/image/merrisa.jpg"/>
                                <p>Mariessa Pinto</p>
                            </section>

                            <section className={styles.jerry_section}>
                                <img src="/image/jerryon.png"/>
                                <p>Jerry On</p>
                            </section>

                            <section className={styles.takami_section}>
                                <img src="/image/takami.jpg"/>
                                <p>Takami Inagaki</p>
                            </section>

                            <section className={styles.khalil_section}>
                                <img src="/image/khalil.jpg"/>
                                <p>Khalil Olaes</p>
                            </section>
                        </div>
                    </div>
                </div>
            </main>

<div className={styles.footer}>
<Footer/>
</div>
        
        </>
    )
}