import Link from "next/link";
import Image from "next/image";
import Head from 'next/head'
import styles from '../styles/thankYou.module.css'

export default function Results(){

    return(
        <>
        <Head>
        <title>Time Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg"/>
      </Head>


<main className={styles.thankyouPage_main}>

<img className={styles.thankYou_logo} src="/image/logo.svg"/>
 
<h1>Thank You for your feedback</h1>

<div className={styles.back_to_home_button}>
<a href="/"><button className={styles.button}>Go back to Home</button></a>
</div>
</main>
        
        </>
    )
}