import Link from "next/link";
import Image from "next/image";
import Head from 'next/head'
import styles from '../styles/about.module.css'
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export default function Results(){

    return(
        <>

       <Head>
        <title>Time Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg"/>
      </Head>
  

<Header/>

<main className={styles.about_main}>

<div className={styles.video}>
<video width="1000px" autoPlay controls>
<source src="/video/videoIDSP.mp4" type="video/mp4" />
</video>
</div>

<div className={styles.about_texts}>
 <p>Time together is a fun and collaborative calendar app. </p>

<p> Keep track of your daily, weekly, monthly and yearly
    schedules through an online interface that is 
    accessible on your phone, tablet and pc. Manage 
    your tasks easier with a clean visual calendar, 
    customize events with colors and emojis.
</p>
<p>
    You have a new feature that allows users access 
    to calendar rooms which is a shared calender for your 
    friends and family.
</p>
<p>
    In each calendar room, members can be assigned 
    into events and events are visible to only people within the group.
</p>
<p>
    Need to chat? No problem!
</p>
<p>
    Time together has a chat service where 
    you can chat with friends and family. No matter the day or time, 
    Time Together can be use any time of the day and you can spend 
    time together with friends and family on this new calendar app!</p>
</div>
</main>
        
<div className={styles.footer}>
<Footer/>
</div>

        </>
    )
}